version: '3.8'  # Versión del archivo compose

services:
  backend:       # Nombre del servicio (puedes llamarlo como quieras)
    build: .  # Ruta al Dockerfile
    ports:
      - "8080:8180"  # Puerto externo:interno
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/valpogo
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1122aaBB
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql  # Espera que mysql se levante antes

  mysql:
    image: mysql:8  # Usa una imagen oficial de MySQL
    ports:
      - "3306:3306"  # Puerto de la base de datos
    environment:
      MYSQL_DATABASE: valpogo
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1122aaBB
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql  # Guarda datos aunque se reinicie

volumes:
  mysql_data:  # Define el volumen que se usa en mysql
